apiVersion: v1
kind: Service
metadata:
  name: {{ include "logstash.fullname" . }}
  labels:
    app: {{ include "logstash.name" . }}
    release: {{ .Release.Name }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: 5044
      protocol: TCP
      name: beats
  selector:
    app: {{ include "logstash.name" . }}
    release: {{ .Release.Name }} 