server:
  port: 8080

spring:
  application:
    name: api-gateway

  cloud:
    gateway:
      routes:
        - id: front-ui
          uri: http://localhost:8081
          predicates:
            - Path=/front/**
          filters:
            - AddRequestHeader=X-Gateway, api-gateway
            - StripPrefix=1
    compatibility-verifier:
      enabled: false

  tracing:
    sampling:
      probability: 1.0
    otlp:
      endpoint: http://localhost:4318

logging:
  pattern:
    level: "%5p [${spring.application.name:},traceId=%X{traceId},spanId=%X{spanId}]"

management:
  tracing:
    enabled: true
  endpoints:
    web:
      exposure:
        include: health,info
  endpoint:
    health:
      show-details: always

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka
