server:
  port: 8081

spring:
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: http://keycloak:8090/realms/bank-realm
  thymeleaf:
    cache: false

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka

gateway_service_url: http://api-gateway:8080/api

clients:
  accounts:
    uri: ${gateway_service_url}
  exchange:
    uri: ${gateway_service_url}
  cash:
    uri: ${gateway_service_url}
  transfer:
    uri: ${gateway_service_url}