{{- if .Values.serviceAccount.create -}}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "kafka-init.serviceAccountName" . }}
  labels:
    {{- include "kafka-init.labels" . | nindent 4 }}
{{- end }} 