services:
  postgres:
    image: postgres:17
    container_name: postgres
    environment:
      POSTGRES_DB: keycloak
      POSTGRES_USER: keycloak
      POSTGRES_PASSWORD: keycloakpassword
    expose:
      - "5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - bank

  keycloak:
    image: quay.io/keycloak/keycloak:21.1.1
    container_name: keycloak
    command: start-dev
    environment:
      KC_DB: postgres
      KC_DB_URL_HOST: postgres
      KC_DB_URL_PORT: 5432
      KC_DB_USERNAME: keycloak
      KC_DB_PASSWORD: keycloakpassword
      KEYCLOAK_ADMIN: admin
      KEYCLOAK_ADMIN_PASSWORD: admin
      KC_HOSTNAME_STRICT: "false"
      KC_HTTP_ENABLED: "true"
    ports:
      - "8090:8080"
    depends_on:
      - postgres
    networks:
      - bank

  discovery-service:
    container_name: discovery-service
    build:
      context: .
      dockerfile: discovery-service/Dockerfile
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8761/actuator/health"]
      interval: 10s
      timeout: 5s
      retries: 20
    expose:
      - "8761"
    networks:
      - bank

  config-service:
    container_name: config-service
    build:
      context: .
      dockerfile: config-service/Dockerfile
    healthcheck:
      test: [ "CMD", "curl", "-f", "http://localhost:8888/actuator/health" ]
      interval: 10s
      timeout: 5s
      retries: 20
    expose:
      - "8888"
    depends_on:
      - discovery-service
    networks:
      - bank

  api-gateway:
    container_name: api-gateway
    build:
      context: .
      dockerfile: api-gateway/Dockerfile
    ports:
      - "8080:8080"
    environment:
      SPRING_SECURITY_OAUTH2_CLIENT_REGISTRATION_KEYCLOAK_CLIENT_SECRET: ${KEYCLOAK_GATEWAY_CLIENT_SECRET}
    depends_on:
      keycloak:
        condition: service_healthy
      config-service:
        condition: service_healthy
      discovery-service:
        condition: service_healthy
    networks:
      - bank

  accounts-service:
    container_name: accounts-service
    build:
      context: .
      dockerfile: accounts-service/Dockerfile
    expose:
      - "8085"
    depends_on:
      keycloak:
        condition: service_healthy
      config-service:
        condition: service_healthy
      discovery-service:
        condition: service_healthy
    networks:
      - bank

  front-ui:
    container_name: front-ui
    build:
      context: .
      dockerfile: front-ui/Dockerfile
    expose:
      - "8081"
    environment:
      KEYCLOAK_FRONT_CLIENT_SECRET: ${KEYCLOAK_FRONT_CLIENT_SECRET}
    depends_on:
      keycloak:
        condition: service_healthy
    networks:
      - bank

  cash-service:
    container_name: cash-service
    build:
      context: .
      dockerfile: cash-service/Dockerfile
    expose:
      - "8084"
    depends_on:
      keycloak:
        condition: service_healthy
      config-service:
        condition: service_healthy
      discovery-service:
        condition: service_healthy
      accounts-service:
        condition: service_started
    networks:
      - bank

  transfer-service:
    container_name: transfer-service
    build:
      context: .
      dockerfile: transfer-service/Dockerfile
    expose:
      - "8088"
    depends_on:
      keycloak:
        condition: service_healthy
      config-service:
        condition: service_healthy
      discovery-service:
        condition: service_healthy
      accounts-service:
        condition: service_started
    networks:
      - bank

  blocker-service:
    container_name: blocker-service
    build:
      context: .
      dockerfile: blocker-service/Dockerfile
    expose:
      - "8083"
    depends_on:
      keycloak:
        condition: service_healthy
      config-service:
        condition: service_healthy
      discovery-service:
        condition: service_healthy
    networks:
      - bank

  exchange-generator-service:
    container_name: exchange-generator-service
    build:
      context: .
      dockerfile: exchange-generator-service/Dockerfile
    expose:
      - "8086"
    depends_on:
      config-service:
        condition: service_healthy
      discovery-service:
        condition: service_healthy
    networks:
      - bank

  exchange-service:
    container_name: exchange-service
    build:
      context: .
      dockerfile: exchange-service/Dockerfile
    expose:
      - "8082"
    depends_on:
      keycloak:
        condition: service_healthy
      config-service:
        condition: service_healthy
      discovery-service:
        condition: service_healthy
      accounts-service:
        condition: service_started
      exchange-generator-service:
        condition: service_started
    networks:
      - bank

  notifications-service:
    container_name: notifications-service
    build:
      context: .
      dockerfile: notifications-service/Dockerfile
    expose:
      - "8087"
    depends_on:
      keycloak:
        condition: service_healthy
      config-service:
        condition: service_healthy
      discovery-service:
        condition: service_healthy
    networks:
      - bank

networks:
  bank:
    driver: bridge