apiVersion: monitoring.coreos.com/v1
kind: PrometheusRule
metadata:
  name: prometheus-alerts
  labels:
    app: prometheus
spec:
  groups:
    - name: example.rules
      rules:
        - alert: HighErrorRate
          expr: sum(rate(http_server_requests_seconds_count{outcome="SERVER_ERROR"}[1m])) by (service) > 1
          for: 2m
          labels:
            severity: warning
          annotations:
            summary: "Высокий уровень 5xx ошибок на сервисе {{ $labels.service }}"
            description: "Больше 1 ошибки в секунду (5xx) на сервисе {{ $labels.service }} в течение 2 минут." 