apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "prometheus.fullname" . }}-config
  labels:
    app: {{ include "prometheus.name" . }}
    release: {{ .Release.Name }}
data:
  prometheus.yml: |
    global:
      scrape_interval: 15s
    scrape_configs:
      - job_name: 'kubernetes-services'
        kubernetes_sd_configs:
          - role: endpoints
        relabel_configs:
          - source_labels: [__meta_kubernetes_namespace]
            action: keep
            regex: .*
          - source_labels: [__meta_kubernetes_service_label_app]
            action: keep
            regex: .*
          - source_labels: [__meta_kubernetes_service_port_name]
            action: keep
            regex: http
        metric_relabel_configs:
          - source_labels: [__name__]
            regex: '.*'
            action: keep
      - job_name: 'spring-actuator'
        metrics_path: /actuator/prometheus
        kubernetes_sd_configs:
          - role: endpoints
        relabel_configs:
          - source_labels: [__meta_kubernetes_service_label_app]
            action: keep
            regex: .* 