spring:
  application:
    name: exchange-service

  config:
    import: optional:configtree:/etc/config/

  kafka:
    bootstrap-servers: bank-kafka:9092
    consumer:
      group-id: exchange-service-group
      auto-offset-reset: latest
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      enable-auto-commit: true
      max-poll-records: 1
      isolation-level: read-committed

cloud:
  config:
    name: exchange-service

kafka:
  topics:
    exchange-rate-events: exchange-rate-events

management:
  tracing:
    enabled: true
    sampling:
      probability: 1.0
    propagation:
      type: w3c
    otlp:
      enabled: false
    zipkin:
      enabled: true
      endpoint: http://zipkin:9411/api/v2/spans
  endpoints:
    web:
      exposure:
        include: health,info,prometheus
  metrics:
    enable:
      all: true
  endpoint:
    prometheus:
      enabled: true