apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "accounts-service.fullname" . }}
  labels:
    {{- include "accounts-service.labels" . | nindent 4 }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      {{- include "accounts-service.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      labels:
        {{- include "accounts-service.selectorLabels" . | nindent 8 }}
    spec:
      serviceAccountName: {{ include "accounts-service.fullname" . }}
      containers:
        - name: {{ .Chart.Name }}
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag | default .Chart.AppVersion }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          ports:
            - name: http
              containerPort: {{ .Values.service.port }}
              protocol: TCP
          livenessProbe:
            httpGet:
              path: {{ .Values.probes.liveness.path }}
              port: http
            initialDelaySeconds: {{ .Values.probes.liveness.initialDelaySeconds }}
            periodSeconds: {{ .Values.probes.liveness.periodSeconds }}
            timeoutSeconds: {{ .Values.probes.liveness.timeoutSeconds }}
            failureThreshold: {{ .Values.probes.liveness.failureThreshold }}
          readinessProbe:
            httpGet:
              path: {{ .Values.probes.readiness.path }}
              port: http
            initialDelaySeconds: {{ .Values.probes.readiness.initialDelaySeconds }}
            periodSeconds: {{ .Values.probes.readiness.periodSeconds }}
            timeoutSeconds: {{ .Values.probes.readiness.timeoutSeconds }}
            failureThreshold: {{ .Values.probes.readiness.failureThreshold }}
          resources:
            {{- toYaml .Values.resources | nindent 12 }}
          env:
            - name: SPRING_PROFILES_ACTIVE
              value: {{ .Values.spring.profiles.active | default "default" }}
            - name: SPRING_DATASOURCE_URL
              value: {{ .Values.spring.datasource.url }}
            - name: SPRING_DATASOURCE_USERNAME
              valueFrom:
                secretKeyRef:
                  name: {{ include "accounts-service.fullname" . }}
                  key: postgresql-user
            - name: SPRING_DATASOURCE_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: {{ include "accounts-service.fullname" . }}
                  key: postgresql-password
            - name: SPRING_R2DBC_URL
              value: {{ .Values.spring.r2dbc.url }}
            - name: SPRING_R2DBC_USERNAME
              valueFrom:
                secretKeyRef:
                  name: {{ include "accounts-service.fullname" . }}
                  key: postgresql-user
            - name: SPRING_R2DBC_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: {{ include "accounts-service.fullname" . }}
                  key: postgresql-password
            - name: SPRING_JPA_PROPERTIES_HIBERNATE_DIALECT
              value: {{ .Values.spring.jpa.properties.hibernate.dialect }}
            - name: SPRING_JPA_HIBERNATE_DDL_AUTO
              value: {{ .Values.spring.jpa.hibernate.ddl_auto }}
            - name: SPRING_JPA_SHOW_SQL
              value: {{ .Values.spring.jpa.show_sql | quote }}
            - name: SPRING_LIQUIBASE_URL
              value: {{ .Values.spring.liquibase.url }}
            - name: SPRING_LIQUIBASE_USER
              valueFrom:
                secretKeyRef:
                  name: {{ include "accounts-service.fullname" . }}
                  key: postgresql-user
            - name: SPRING_LIQUIBASE_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: {{ include "accounts-service.fullname" . }}
                  key: postgresql-password
            - name: LOGGING_LEVEL_ROOT
              value: {{ .Values.logging.level.root }}
            - name: LOGGING_LEVEL_RU_INDIV_BANK
              value: {{ .Values.logging.level.ru_indiv_bank }}
            - name: EUREKA_CLIENT_SERVICEURL_DEFAULTZONE
              value: {{ .Values.eureka.client.service_url.default_zone }}
          volumeMounts:
            - name: config-volume
              mountPath: /app/config
      volumes:
        - name: config-volume
          configMap:
            name: {{ include "accounts-service.fullname" . }}
