apiVersion: v1
kind: Secret
metadata:
  name: {{ include "accounts-service.fullname" . }}
  labels:
    {{- include "accounts-service.labels" . | nindent 4 }}
type: Opaque
data:
  postgresql-user: {{ .Values.secrets.postgresql.user | b64enc }}
  postgresql-password: {{ .Values.secrets.postgresql.password | b64enc }}
