apiVersion: v1
kind: Secret
metadata:
  name: {{ include "notifications-service.fullname" . }}
  labels:
    {{- include "notifications-service.labels" . | nindent 4 }}
type: Opaque
data:
  postgresql-user: {{ .Values.secrets.postgresql.user | b64enc }}
  postgresql-password: {{ .Values.secrets.postgresql.password | b64enc }}
  mail-username: {{ .Values.secrets.mail.username | b64enc }}
  mail-password: {{ .Values.secrets.mail.password | b64enc }} 