apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "front-ui.fullname" . }}
  labels:
    {{- include "front-ui.labels" . | nindent 4 }}
data:
  application.yml: |
    server:
      port: {{ .Values.service.port }}
      servlet:
        context-path: {{ .Values.service.contextPath }}

    spring:
      security:
        oauth2:
          resourceserver:
            jwt:
              issuer-uri: {{ .Values.spring.security.oauth2.resourceserver.jwt.issuer_uri }}
      thymeleaf:
        cache: {{ .Values.spring.thymeleaf.cache }}

    eureka:
      client:
        service-url:
          defaultZone: {{ .Values.eureka.client.service_url.default_zone }}

    gateway_service_url: {{ .Values.gateway.service_url }}

    clients:
      accounts:
        uri: ${gateway_service_url}
      exchange:
        uri: ${gateway_service_url}
      cash:
        uri: ${gateway_service_url}
      transfer:
        uri: ${gateway_service_url}

    logging:
      level:
        root: {{ .Values.logging.level.root }}
        ru_indiv_bank: {{ .Values.logging.level.ru_indiv_bank }} 