apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "front-ui.fullname" . }}
  labels:
    {{- include "front-ui.labels" . | nindent 4 }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      {{- include "front-ui.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      labels:
        {{- include "front-ui.selectorLabels" . | nindent 8 }}
    spec:
      serviceAccountName: {{ include "front-ui.fullname" . }}
      containers:
        - name: {{ .Chart.Name }}
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag | default .Chart.AppVersion }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          ports:
            - name: http
              containerPort: {{ .Values.service.port }}
              protocol: TCP
          livenessProbe:
            httpGet:
              path: {{ .Values.probes.liveness.path }}
              port: http
            initialDelaySeconds: {{ .Values.probes.liveness.initialDelaySeconds }}
            periodSeconds: {{ .Values.probes.liveness.periodSeconds }}
            timeoutSeconds: {{ .Values.probes.liveness.timeoutSeconds }}
            failureThreshold: {{ .Values.probes.liveness.failureThreshold }}
          readinessProbe:
            httpGet:
              path: {{ .Values.probes.readiness.path }}
              port: http
            initialDelaySeconds: {{ .Values.probes.readiness.initialDelaySeconds }}
            periodSeconds: {{ .Values.probes.readiness.periodSeconds }}
            timeoutSeconds: {{ .Values.probes.readiness.timeoutSeconds }}
            failureThreshold: {{ .Values.probes.readiness.failureThreshold }}
          env:
            - name: SERVER_PORT
              value: {{ .Values.service.port | quote }}
            - name: SERVER_SERVLET_CONTEXT_PATH
              value: {{ .Values.service.contextPath }}
            - name: SPRING_SECURITY_OAUTH2_RESOURCESERVER_JWT_ISSUER_URI
              value: {{ .Values.spring.security.oauth2.resourceserver.jwt.issuer_uri }}
            - name: SPRING_THYMELEAF_CACHE
              value: {{ .Values.spring.thymeleaf.cache | quote }}
            - name: EUREKA_CLIENT_SERVICEURL_DEFAULTZONE
              value: {{ .Values.eureka.client.service_url.default_zone }}
            - name: GATEWAY_SERVICE_URL
              value: {{ .Values.gateway.service_url }}
            - name: LOGGING_LEVEL_ROOT
              value: {{ .Values.logging.level.root }}
            - name: LOGGING_LEVEL_RU_INDIV_BANK
              value: {{ .Values.logging.level.ru_indiv_bank }}
          resources:
            {{- toYaml .Values.resources | nindent 12 }}
          volumeMounts:
            - name: config-volume
              mountPath: /app/config
      volumes:
        - name: config-volume
          configMap:
            name: {{ include "front-ui.fullname" . }}
