apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "transfer-service.fullname" . }}
  labels:
    {{- include "transfer-service.labels" . | nindent 4 }}
data:
  application.yml: |
    server:
      port: {{ .Values.service.port }}
      servlet:
        context-path: {{ .Values.service.contextPath }}

    spring:
      security:
        oauth2:
          resourceserver:
            jwt:
              issuer-uri: {{ .Values.spring.security.oauth2.resourceserver.jwt.issuer_uri }}
      # Kafka configuration
      kafka:
        bootstrap-servers: {{ .Values.spring.kafka.bootstrap-servers }}
        producer:
          key-serializer: {{ .Values.spring.kafka.producer.key-serializer }}
          value-serializer: {{ .Values.spring.kafka.producer.value-serializer }}
          acks: {{ .Values.spring.kafka.producer.acks }}
          retries: {{ .Values.spring.kafka.producer.retries }}
          batch-size: {{ .Values.spring.kafka.producer.batch-size }}
          linger-ms: {{ .Values.spring.kafka.producer.linger-ms }}
          buffer-memory: {{ .Values.spring.kafka.producer.buffer-memory }}
          enable-idempotence: {{ .Values.spring.kafka.producer.enable-idempotence }}
          max-in-flight-requests-per-connection: {{ .Values.spring.kafka.producer.max-in-flight-requests-per-connection }}

    eureka:
      client:
        service-url:
          defaultZone: {{ .Values.eureka.client.service_url.default_zone }}

    # Kafka topics
    kafka:
      topics:
        notification-events: {{ .Values.kafka.topics.notification-events }}

    logging:
      level:
        root: {{ .Values.logging.level.root }}
        ru_indiv_bank: {{ .Values.logging.level.ru_indiv_bank }} 