apiVersion: v1
kind: Service
metadata:
  name: {{ include "kibana.fullname" . }}
  labels:
    app: {{ include "kibana.name" . }}
    release: {{ .Release.Name }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: 5601
      protocol: TCP
      name: http
  selector:
    app: {{ include "kibana.name" . }}
    release: {{ .Release.Name }} 