apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "blocker-service.fullname" . }}
  labels:
    {{- include "blocker-service.labels" . | nindent 4 }}
data:
  application.yml: |-
    server:
      port: {{ .Values.service.port }}
      servlet:
        context-path: {{ .Values.service.contextPath }}

    spring:
      security:
        oauth2:
          resourceserver:
            jwt:
              issuer-uri: {{ .Values.spring.security.oauth2.resourceserver.jwt.issuer_uri }}

    eureka:
      client:
        service-url:
          defaultZone: {{ .Values.eureka.client.service_url.default_zone }}

    logging:
      level:
        root: {{ .Values.logging.level.root }}
        ru.indiv.bank: {{ .Values.logging.level.ru_indiv_bank }} 