spring:
  application:
    name: notifications-service

  config:
    import: optional:configtree:/etc/config/

  # Kafka configuration
  kafka:
    bootstrap-servers: bank-kafka:9092
    consumer:
      group-id: notifications-service-group
      auto-offset-reset: earliest
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      enable-auto-commit: false
      isolation-level: read-committed
    producer:
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.apache.kafka.common.serialization.StringSerializer
      acks: all
      retries: 3
      batch-size: 16384
      linger-ms: 1
      buffer-memory: 33554432

cloud:
  config:
    name: notifications-service

# Kafka topics
kafka:
  topics:
    notification-events: notification-events