apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "cash-service.fullname" . }}
  labels:
    {{- include "cash-service.labels" . | nindent 4 }}
data:
  application.yml: |-
    server:
      port: {{ .Values.service.port }}
      servlet:
        context-path: {{ .Values.service.contextPath }}

    spring:
      security:
        oauth2:
          resourceserver:
            jwt:
              issuer-uri: {{ .Values.spring.security.oauth2.resourceserver.jwt.issuer_uri }}
      r2dbc:
        url: {{ .Values.spring.r2dbc.url }}
        pool:
          enabled: {{ .Values.spring.r2dbc.pool.enabled }}
          initial-size: {{ .Values.spring.r2dbc.pool.initial_size }}
          max-size: {{ .Values.spring.r2dbc.pool.max_size }}
          max-idle-time: {{ .Values.spring.r2dbc.pool.max_idle_time }}
          max-life-time: {{ .Values.spring.r2dbc.pool.max_life_time }}
          validation-query: {{ .Values.spring.r2dbc.pool.validation_query }}
      datasource:
        url: {{ .Values.spring.datasource.url }}
      jpa:
        show-sql: {{ .Values.spring.jpa.show_sql }}
        hibernate:
          ddl-auto: {{ .Values.spring.jpa.hibernate.ddl_auto }}
        properties:
          hibernate:
            dialect: {{ .Values.spring.jpa.properties.hibernate.dialect }}
            format_sql: {{ .Values.spring.jpa.properties.hibernate.format_sql }}
      liquibase:
        change-log: {{ .Values.spring.liquibase.change_log }}
        default-schema: {{ .Values.spring.liquibase.default_schema }}
        url: {{ .Values.spring.liquibase.url }}
        enabled: {{ .Values.spring.liquibase.enabled }}
      kafka:
        bootstrap-servers: {{ .Values.spring.kafka.bootstrap-servers }}
        producer:
          key-serializer: {{ .Values.spring.kafka.producer.key-serializer }}
          value-serializer: {{ .Values.spring.kafka.producer.value-serializer }}
          acks: {{ .Values.spring.kafka.producer.acks }}
          retries: {{ .Values.spring.kafka.producer.retries }}
          batch-size: {{ .Values.spring.kafka.producer.batch-size }}
          linger-ms: {{ .Values.spring.kafka.producer.linger-ms }}
          buffer-memory: {{ .Values.spring.kafka.producer.buffer-memory }}
          enable-idempotence: {{ .Values.spring.kafka.producer.enable-idempotence }}
          max-in-flight-requests-per-connection: {{ .Values.spring.kafka.producer.max-in-flight-requests-per-connection }}

    eureka:
      client:
        service-url:
          defaultZone: {{ .Values.eureka.client.service_url.default_zone }}

    kafka:
      topics:
        notification-events: {{ .Values.kafka.topics.notification-events }}

    logging:
      level:
        root: {{ .Values.logging.level.root }}
        ru.indiv.bank: {{ .Values.logging.level.ru_indiv_bank }} 