replicaCount: 1

image:
  repository: xINDYx/cash-service
  pullPolicy: IfNotPresent
  tag: ""

service:
  type: ClusterIP
  port: 8084
  contextPath: /api/cash

spring:
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer_uri: http://keycloak:8090/realms/bank-realm
  r2dbc:
    url: r2dbc:postgresql://bank-postgres:5432/cash
    pool:
      enabled: true
      initial_size: 10
      max_size: 50
      max_idle_time: 30s
      max_life_time: 10m
      validation_query: SELECT 1
  datasource:
    url: jdbc:postgresql://bank-postgres:5432/cash
  jpa:
    show_sql: true
    hibernate:
      ddl_auto: validate
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        format_sql: true
  liquibase:
    change_log: classpath:/db/changelog/db.changelog-master.yml
    default_schema: public
    url: jdbc:postgresql://bank-postgres:5432/cash
    enabled: true
  # Kafka configuration
  kafka:
    bootstrap-servers: bank-kafka:9092
    producer:
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.apache.kafka.common.serialization.StringSerializer
      acks: all
      retries: 3
      batch-size: 16384
      linger-ms: 1
      buffer-memory: 33554432
      enable-idempotence: true
      max-in-flight-requests-per-connection: 5

eureka:
  client:
    service_url:
      default_zone: http://discovery-service:8761/eureka

# Kafka topics
kafka:
  topics:
    notification-events: notification-events

logging:
  level:
    root: INFO
    ru_indiv_bank: DEBUG

resources:
  limits:
    cpu: 1000m
    memory: 1Gi
  requests:
    cpu: 500m
    memory: 512Mi

probes:
  liveness:
    path: /actuator/health/liveness
    initialDelaySeconds: 60
    periodSeconds: 10
    timeoutSeconds: 5
    failureThreshold: 3
  readiness:
    path: /actuator/health/readiness
    initialDelaySeconds: 30
    periodSeconds: 10
    timeoutSeconds: 5
    failureThreshold: 3

autoscaling:
  enabled: true
  minReplicas: 2
  maxReplicas: 4
  targetCPUUtilizationPercentage: 80
  targetMemoryUtilizationPercentage: 80

secrets:
  postgresql:
    user: postgres
    password: postgres

serviceAccount:
  create: true
  name: ""

ingress:
  enabled: false
  className: "nginx"
  annotations: {}
  hosts:
    - host: cash.local
      paths:
        - path: /
          pathType: Prefix
  tls: []