# Production environment configuration
kafka:
  enabled: true
  replicaCount: 3  # Для prod окружения используем 3 реплики для высокой доступности
  persistence:
    enabled: true
    storageClass: ""
    size: 10Gi
    accessModes:
      - ReadWriteOnce
  resources:
    limits:
      cpu: 1500m
      memory: 3Gi
    requests:
      cpu: 750m
      memory: 1.5Gi
  zookeeper:
    enabled: true
    persistence:
      enabled: true
      storageClass: ""
      size: 5Gi
    resources:
      limits:
        cpu: 750m
        memory: 1.5Gi
      requests:
        cpu: 375m
        memory: 768Mi
  externalAccess:
    enabled: false
  service:
    type: ClusterIP
  deleteTopicEnable: false  # В prod отключаем автоматическое удаление топиков
  autoCreateTopicsEnable: true
  numPartitions: 3
  defaultReplicationFactor: 3
  offsets:
    topic:
      replication:
        factor: 3
  transaction:
    state:
      log:
        replication:
          factor: 3
  logRetentionHours: 168  # 7 дней
  logRetentionBytes: -1
  logRetentionCheckIntervalMs: 300000

# Настройки для микросервисов в prod окружении
accounts-service:
  replicaCount: 3
  resources:
    limits:
      cpu: 1000m
      memory: 1Gi
    requests:
      cpu: 500m
      memory: 512Mi

blocker-service:
  replicaCount: 3
  resources:
    limits:
      cpu: 1000m
      memory: 1Gi
    requests:
      cpu: 500m
      memory: 512Mi

cash-service:
  replicaCount: 3
  resources:
    limits:
      cpu: 1000m
      memory: 1Gi
    requests:
      cpu: 500m
      memory: 512Mi

exchange-service:
  replicaCount: 3
  resources:
    limits:
      cpu: 1000m
      memory: 1Gi
    requests:
      cpu: 500m
      memory: 512Mi

exchange-generator-service:
  replicaCount: 3
  resources:
    limits:
      cpu: 1000m
      memory: 1Gi
    requests:
      cpu: 500m
      memory: 512Mi

front-ui:
  replicaCount: 3
  resources:
    limits:
      cpu: 1000m
      memory: 1Gi
    requests:
      cpu: 500m
      memory: 512Mi

notifications-service:
  replicaCount: 3
  resources:
    limits:
      cpu: 1000m
      memory: 1Gi
    requests:
      cpu: 500m
      memory: 512Mi

transfer-service:
  replicaCount: 3
  resources:
    limits:
      cpu: 1000m
      memory: 1Gi
    requests:
      cpu: 500m
      memory: 512Mi 