# Test environment configuration
kafka:
  enabled: true
  replicaCount: 2  # Для test окружения используем 2 реплики
  persistence:
    enabled: true
    storageClass: ""
    size: 6Gi
    accessModes:
      - ReadWriteOnce
  resources:
    limits:
      cpu: 750m
      memory: 1.5Gi
    requests:
      cpu: 375m
      memory: 768Mi
  zookeeper:
    enabled: true
    persistence:
      enabled: true
      storageClass: ""
      size: 3Gi
    resources:
      limits:
        cpu: 375m
        memory: 768Mi
      requests:
        cpu: 187m
        memory: 384Mi
  externalAccess:
    enabled: false
  service:
    type: ClusterIP
  deleteTopicEnable: true
  autoCreateTopicsEnable: true
  numPartitions: 2
  defaultReplicationFactor: 2
  offsets:
    topic:
      replication:
        factor: 2
  transaction:
    state:
      log:
        replication:
          factor: 2
  logRetentionHours: 72
  logRetentionBytes: -1
  logRetentionCheckIntervalMs: 300000

# Настройки для микросервисов в test окружении
accounts-service:
  replicaCount: 2
  resources:
    limits:
      cpu: 750m
      memory: 768Mi
    requests:
      cpu: 375m
      memory: 384Mi

blocker-service:
  replicaCount: 2
  resources:
    limits:
      cpu: 750m
      memory: 768Mi
    requests:
      cpu: 375m
      memory: 384Mi

cash-service:
  replicaCount: 2
  resources:
    limits:
      cpu: 750m
      memory: 768Mi
    requests:
      cpu: 375m
      memory: 384Mi

exchange-service:
  replicaCount: 2
  resources:
    limits:
      cpu: 750m
      memory: 768Mi
    requests:
      cpu: 375m
      memory: 384Mi

exchange-generator-service:
  replicaCount: 2
  resources:
    limits:
      cpu: 750m
      memory: 768Mi
    requests:
      cpu: 375m
      memory: 384Mi

front-ui:
  replicaCount: 2
  resources:
    limits:
      cpu: 750m
      memory: 768Mi
    requests:
      cpu: 375m
      memory: 384Mi

notifications-service:
  replicaCount: 2
  resources:
    limits:
      cpu: 750m
      memory: 768Mi
    requests:
      cpu: 375m
      memory: 384Mi

transfer-service:
  replicaCount: 2
  resources:
    limits:
      cpu: 750m
      memory: 768Mi
    requests:
      cpu: 375m
      memory: 384Mi 